#!/bin/bash
# verif-gate — Определение класса верификации задачи
# Использование: bash ~/iwe-platform/scripts/skills/verif-gate.sh
# Применяется при каждом новом задании (WP Gate)

echo "=== Verif Gate: класс верификации ==="
echo ""
echo "Задай 3 вопроса:"
echo ""
echo "1. Результат очевиден? (уверен без проверки)"
echo "   → Да: trivial"
echo "   → Нет: ↓"
echo ""
echo "2. Есть дешёвый автомат проверки? (тест, diff, grep)"
echo "   → Да: closed-loop"
echo "   → Нет: ↓"
echo ""
echo "3. Решение известно? (знаю что должно получиться)"
echo "   → Да: open-loop"
echo "   → Нет: problem-framing"
echo ""
echo "Режимы:"
echo "- trivial → flash, без captures"
echo "- closed-loop → flash/pro, captures по паттерну"
echo "- open-loop → pro, captures обязательны"
echo "- problem-framing → pro, вопросы > ответы"
echo ""
echo "Объяви ритуал:"
echo "> Роль пользователя:"
echo "> Роль агента:"
echo "> Работа:"
echo "> РП:"
echo "> Класс верификации:"
echo "> Метод:"
echo "> Оценка: ~Xh"
echo "> Модель: [текущая] — рекомендую [модель] ([причина])"
